### ISSUE TITLE
Is there a way to convert the EnemyVisiblity.cs to work on a 2d plane? X and y and not z?

### ISSUE THREAD

**Issue by FMastro** [thesecretlab/unity-game-development-cookbook-1e#1]
Is there a way to convert the EnemyVisiblity.cs to work on a 2d plane? X and y and not z? 
I'm trying to retro this for a 2d game but the arc is going into z space.

**Comment by desplesda** [comment]
If you're viewing a game down the Z axis, you can force everything to the same plane by making the Z coordinate of the vector you provide to `CheckVisibilityToPoint` be equal to that of the object that has the `EnemyVisibility` component.

**Comment by FMastro** [comment]
> If you're viewing a game down the Z axis, you can force everything to the same plane by making the Z coordinate of the vector you provide to `CheckVisibilityToPoint` be equal to that of the object that has the `EnemyVisibility` component.

thanks, I'll mess around with that. Would that adjust the visual arc in the editor? That thing is great.  I was trying to get the visual arc to show up right.

**Comment by FMastro** [comment]
![image](https://user-images.githubusercontent.com/927036/87329841-a01d3b00-c505-11ea-8752-e6480f723075.png)
See how the arc goes into the Z axis of my 2d game.

I tried to change some things to use RatCast2D, instead of 3d, but seems beyond me.

```
// Stores information about anything we hit
        RaycastHit2D hit = Physics2D.Raycast(transform.position, directionToTarget, rayDistance);

        // Perform the raycast. Did it hit anything?
        if (hit) { //Physics.Raycast(ray, out hit, rayDistance)
            Debug.Log($"We Hit: {hit.collider.name}");
            // We hit something. 
            if (hit.collider.transform == target) {
```

I also tried to use the other method

`targetIsVisible = CheckVisibilityToPoint(target.transform.position);`

**Comment by desplesda** [comment]
Take a look at the `Handles.DrawSolidArc` call in `EnemyVisibilityEditor.OnSceneGUI` - the second parameter is the up direction of the arc. The arc is drawn at 90° to the up direction.

**Comment by desplesda** [comment]
I'm going to close this issue because it looks like your question is answered, but please post here if you need more info!
